### ISSUE TITLE
Assert config file field types

### ISSUE THREAD

**Issue by backus** [mbj/devtools#96]
#91 refactored the flay implementation and killed some mutations along the way.  An unintended side effect was that configuration that specifies `total_score` as a float like so

```yaml
---
threshold: 12
total_score: 88.0
```

as opposed to an integer

```yaml
---
threshold: 12
total_score: 88
```

now produces

> Flay total is now 88, but expected 88 bundle exec rake ci returned exit code 1

To avoid issues like this, we should assert expected types on configuration load.
